### ISSUE TITLE
Misprint in a package version for python 3.6

### ISSUE THREAD

**Issue by tkrishtop** [thread/flask-fluentd#11]
```
myniceapp      | Traceback (most recent call last):
myniceapp      |   File "./run.py", line 9, in <module>
myniceapp      |     from flask_fluentd import Fluentd
myniceapp      |   File "/usr/local/lib/python3.6/site-packages/flask_fluentd.py", line 47
myniceapp      |     except Exception, e:
myniceapp      |                     ^
myniceapp      | SyntaxError: invalid syntax
```

**Comment by prophile** [comment]
Hi @tkrishtop, this was fixed a couple of months ago: are you installing the most recent version?

**Comment by tkrishtop** [comment]
Hello @prophile ,

it's in docker from python3.6-slim, but yes, the last version:

Dockerfile :

```
FROM python:3.6-slim
COPY requirements.txt /tmp/myniceapp/requirements.txt
RUN pip install -r /tmp/myniceapp/requirements.txt
```

requirements.txt :

```
flask-fluentd
```
